### ISSUE TITLE
ID / Accountfolder not unique enough

### ISSUE THREAD

**Issue by demlak** [datamints/kirby-plugin_ldap#1]
hey.. since we have users with same surname and our ldap does not serve UIDs, the ID of the accountfolder and ID looks like `LDAP_lastname_` and thats not unique enough.
i recommend to **generate** UID, instead of loading it from ldap

like 
```
'id'        => "LDAP_".$ldapUser['lastname']."_".substr(uniqid(), 0, 5),
```

**Comment by datamints-off** [comment]
Sorry for the late answer, but as our company stopped using Kirby a while ago, this plugin is not maintained any more.
