### ISSUE TITLE
Wrong parameters for InvalidArgumentException

### ISSUE THREAD

**Issue by demlak** [datamints/kirby-plugin_ldap#2]
in combination with frontend-login via this plugin: https://github.com/kerli81/kirby-securedpages

we get the following error on wrong passwords for line 26 in `classes/Model/LdapUser.php`

```
Wrong parameters for InvalidArgumentException([string $message [, long $code [, Throwable $previous = NULL]]])
```

**Comment by flokuek** [comment]
@demlak Hi, did you ever managed to fix this error message yourself by any chance?

**Comment by flokuek** [comment]
All good, I json_encode the array so it becomes a string.

**Comment by demlak** [comment]
ah well.. we do an exit on wrong password..

line 25: `            exit("Wrong Password");`

**Comment by datamints-off** [comment]
Sorry for the late answer, but as our company stopped using Kirby a while ago, this plugin is not maintained any more.
