### ISSUE TITLE
Error when logging in (Kirby 3.9.4)

### ISSUE THREAD

**Issue by squareclouds** [datamints/kirby-plugin_ldap#4]
hello,

i am getting this error when trying the plugin with the latest kirby 3.9.4. any idea why?

```
null is not an object (evaluating 't.details.challengeDestroyed')
```

![Bildschirmfoto 2023-06-06 um 13 01 00](https://github.com/datamints/kirby-plugin_ldap/assets/9073054/aac68e49-b493-4ab4-baed-e623270f7580)

I can confirm that my LDAP global credentials are working when i run a test via the terminal

**Comment by datamints-off** [comment]
Sorry, but as our company stopped using Kirby a while ago, this plugin is not maintained any more.
